import { Navbar } from '../components/Navbar';
import '../styles/legal.css';

export const PrivacyPolicy = () => {
  return (
    <>
      <Navbar />
      <main className="legal-page">
        <div className="container">
          <div className="legal-header">
            <h1>Data Privacy Policy</h1>
            <p className="legal-updated">Last updated: March 2024</p>
          </div>
          
          <div className="legal-content">
            <section className="legal-section">
              <h2>Definitions</h2>
              <div className="legal-definition">
                <p><strong>"Application"</strong> means the POV Application available on Apple and Android devices.</p>
                
                <p><strong>"Applicable Data Protection Legislation"</strong> means all legislation and regulations, issued by relevant regulatory authorities in England and Wales for the protection of and processing of Personal Data, all as applicable to the Service Provider. This includes without limitation (Retained EU Legislation) Regulation (EU) 2016/679 (United Kingdom General Data Protection Regulation) (UK GDPR)</p>
                
                <p><strong>"Consent"</strong> means any voluntary, speciﬁc and informed expression of will in terms of which permission is given for the processing of Personal Data.</p>
                
                <p><strong>"Company"</strong> means POV Reality Limited, a private company incorporated in accordance with the laws of England and Wales, Company Number: 15457251.</p>
                
                <p><strong>"Data Subject"</strong> means any Person whose Personal Data the Company processes.</p>
                
                <p><strong>"Deemed consent"</strong> in relation to a Data Subject applies if the individual voluntarily provides the Personal Data to the Company for a purpose and it is reasonable that the individual would do so.</p>
                
                <p><strong>"Device"</strong> means any device that can access the Service such as a cellphone or a digital tablet.</p>
                
                <p><strong>"Person"</strong> means an identifiable natural person who can be identified, directly or indirectly.</p>
                
                <p><strong>"Personal Data"</strong> means any information relating to an identified or identifiable natural person ('data subject'); an identifiable natural person is one who can be identified, directly or indirectly, in particular by reference to an identifier such as a name, an identification number, location data, an online identifier or to one or more factors specific to the physical, physiological, genetic, mental, economic, cultural or social identity of that natural person. Personal Data does not include general, statistical, aggregated or anonymised information.</p>
                
                <p><strong>"Policy"</strong> means this policy and any amendments made to it from time to time;</p>
                
                <p><strong>"Processing"</strong> means any operation or activity or any set of operations, whether by automatic means, concerning Personal Data, including:
                the collection, receipt, recording, organisation, collation, storage, updating or modification, retrieval, alteration, consultation or use;
                dissemination by means of transmission, distribution or making available in any other form; or
                merging, linking, as well as restriction, degradation, erasure or destruction of Personal Data;</p>
                
                <p><strong>"Service"</strong> means the streaming and video recording services offered by the Service Provider through its POV Application enabling users to create and share content (first-person videos) and to interact with the content of other users in real-time and also includes virtual reality (VR) technology.</p>
                
                <p><strong>"Usage Data"</strong> refers to data collected automatically, either generated by the use of the Service or from the Service infrastructure itself (for example, the duration of the Data Subject's interaction with the Application.</p>
              </div>
            </section>

            <section className="legal-section">
              <h2>Context and Background</h2>
              <p>The Company promotes the right to protection against unlawful processing of Personal Data. In order to give effect to the right to privacy in accordance with the Applicable Data Protection Legislation, it is the policy of the Company that it will comply with the minimum requirements set forth in clause 4 of this Policy at all times.</p>
            </section>

            <section className="legal-section">
              <h2>Purpose</h2>
              <p>From time to time in the conduct of its business, the Company will come into possession of and will consequently process Personal Data.</p>
              <p>The purpose of this Policy is to record how the Company will process the Personal Data of Data Subjects and, in doing so, comply with the minimum requirements set forth in clause 4 of this Policy.</p>
            </section>

            <section className="legal-section">
              <h2>Minimum Requirements for Processing Personal Data</h2>
              <p>In order for the Company to process Personal Data in a manner which is consistent with the Applicable Data Protection Legislation, the Company shall:</p>
              <ol className="legal-list">
                <li>process the Personal Data lawfully and in a reasonable manner that does not infringe the right to privacy of the Data Subject whose information is being processed;</li>
                <li>process the Personal Data for a specific, explicitly defined and lawful purpose related to a function or activity of the Company;</li>
                <li>process the Personal Data only if, given the purpose for which it is processed, it is adequate, relevant and not excessive and if:
                  <ol className="legal-sublist">
                    <li>the Data Subject whose information will be processed has provided its Consent or Deemed Consent to its information being processed;</li>
                    <li>it is necessary to process the information to comply with an obligation imposed by law on the Company or to protect a legitimate interest of the Company and/or the individual whose information will be processed;</li>
                  </ol>
                </li>
                <li>take reasonable steps to ensure that the individual whose information will be processed is aware of the information that will be processed, the source from which that information will be collected and the purpose for which that information will be processed;</li>
                <li>take reasonable steps to ensure that the information that is processed is complete, accurate, not misleading and updated where necessary;</li>
                <li>take reasonable technical and organisational measures to secure the integrity and confidentiality of the information that is processed so as to prevent the loss, damage or unauthorised destruction of Information and the unlawful access to or processing of information; and</li>
                <li>take reasonable steps to ensure that the individual whose Information will be processed is aware of its rights in and to its information.</li>
              </ol>
            </section>

            <section className="legal-section">
              <h2>Information the Company Collects</h2>
              <ol className="legal-list">
                <li>Personal Data. When the Data Subject signs up as a Spectator or Creator, the Company collects the following information:
                  <ol className="legal-sublist">
                    <li>Email address</li>
                    <li>First name and last name</li>
                    <li>Password</li>
                    <li>Location information, if enabled i.e., Address, State, Province, ZIP/Postal code, City</li>
                    <li>Banking information</li>
                    <li>Usage Data</li>
                  </ol>
                </li>
                <li>Usage Data. Usage Data is collected automatically when using the Service. Usage Data may include information such as the Data Subject's Device's Internet Protocol address (e.g., IP address), browser type, browser version, the nature and type of content the Data Subject interacts when using the Service, the time and date of the interactions, the duration of the interactions, unique device identifiers and other diagnostic data.</li>
                <li>Device Information. When the Data Subject uses a mobile device to access the Service, the Company may collect certain information automatically, including, but not limited to, the type of mobile device, the mobile device unique ID, the IP address of the mobile device, the mobile device's operating system, the type of mobile Internet browser, unique device identifiers and other diagnostic data.</li>
              </ol>
            </section>

            <section className="legal-section">
              <h2>How the Company Uses the Information</h2>
              <ol className="legal-list">
                <li>To provide and improve the Company's Services. The Company regards the lawful and proper processing of Personal Data as crucial to successful service delivery. The Company uses the Data Subject's Personal Data to deliver, maintain, and enhance its services, including personalizing the Data Subject's experience based on specified interests.</li>
                <li>To manage the Data Subject's account. The Company uses the Personal Data collected during the registration process to provide access to different functionalities of the Service that are available to the Data Subject as a registered user.</li>
                <li>To Communicate with the Data Subject. The Company uses the Data Subject's contact information to send updates, promotional campaigns or informative communications related to the Service or functionalities, including the security updates, when necessary or reasonable for their implementation.</li>
                <li>To prevent and detect criminal activity. The Company uses the Data Subject's Personal Data to protect against identify theft, fraud, misuse of and/or damage to the Company's Services and other unlawful activities.</li>
                <li>To Comply with Legal Obligations. The Company may use the Data Subject's Personal Data to comply with legal and regulatory requirements, where applicable.</li>
              </ol>
            </section>

            <section className="legal-section">
              <h2>Retention Periods</h2>
              <p>The time periods for which the Company maintains a record of the Data Subject's Personal Data may vary according to the use or purpose attached to the information. Unless there is a specific legal requirement requiring the Company to keep the information, the Company will not maintain a record of the information for longer than necessary for the purpose for which the information was collected or for which it is to be processed.</p>
            </section>

            <section className="legal-section">
              <h2>Disclosing Personal Data to Third Parties</h2>
              <ol className="legal-list">
                <li>The Customer may provide aggregate statistics about the Company's revenue, customers, traffic patterns and other relevant information to third parties.</li>
                <li>Service Providers. The Company may share the Data Subject's Personal Data with third-party service providers who assist the Company in operating the Application, processing payments, and delivering services to the Data Subject.</li>
                <li>Business Partners. The Company may share the Data Subject's Personal Data with VR companies, sports agencies, and other partners to enhance the Data Subject's experience on the Company's platform.</li>
                <li>Legal requirement in accordance with mandatory law. The Company may disclose the Data Subject's Personal Data pursuant to mandatory law or by order of a judicial or governmental authority.</li>
              </ol>
            </section>

            <section className="legal-section">
              <h2>Rights of Data Subjects</h2>
              <p>The Company will ensure that it makes Data Subjects aware of their rights, as appropriate and specifically with regards to the following:</p>
              <ol className="legal-list">
                <li>The right to access Personal Data
                  <p>Data Subjects have the right to establish whether the Company holds Personal Data related to them, including the right to request access to that Personal Data.</p>
                </li>
                <li>The right to amend or delete Personal Data
                  <p>Data Subjects also have the right to update, correct or delete their Personal Data on reasonable grounds:</p>
                  <ol className="legal-sublist">
                    <li>Account Settings. The Data Subject can update their Personal Data, manage preferences, and control privacy settings through the Application's settings page.</li>
                    <li>Location Sharing. The Data Subject has the option to enable or disable location sharing when live streaming or recording a video.</li>
                    <li>Home Address. The Data Subject has the option to enter their home address details in the Application settings.</li>
                  </ol>
                </li>
                <li>The right to object to the processing of Personal Data
                  <p>Data Subjects have the right on reasonable grounds, to object to the processing of their Personal Data. The Company will consider such requests and may cease to process such Personal Data and may, subject to statutory and contractual record keeping requirements, also destroy the Personal Data.</p>
                </li>
                <li>The right to object to direct marketing
                  <p>Data Subjects have the right to object to their Personal Data being used for the purposes of direct marketing by means of unsolicited electronic communications.</p>
                </li>
                <li>The right to be informed
                  <p>Data Subjects have the right to be informed that their Personal Data is being collected by the Company and should also be notified in any situation where the Company reasonably believes that the Personal Data of Data Subjects has been accessed by unauthorised person/s.</p>
                </li>
              </ol>
            </section>

            <section className="legal-section">
              <h2>Further Processing Limitation</h2>
              <p>Personal Data will not be processed for a secondary purpose unless that processing is compatible with the original purpose. Where the secondary purpose is not compatible with the original purpose, the Company will first obtain additional consent from the Data subject.</p>
            </section>

            <section className="legal-section">
              <h2>Information Quality</h2>
              <ol className="legal-list">
                <li>The Company shall take reasonably practicable steps to ensure that the Personal Data of Data Subjects that it processes is complete, accurate, not misleading and updated where necessary.</li>
                <li>The Company will accordingly request Data Subjects to verify the completeness and accuracy of the Personal Data provided by them from time to time.</li>
              </ol>
            </section>

            <section className="legal-section">
              <h2>Security Safeguards</h2>
              <ol className="legal-list">
                <li>The Company is committed to keeping the Personal Data safe and secure and have appropriate and proportionate organisational and technical measures in place.</li>
                <li>Personal Data is only accessible by authorised personnel with features enacted to prevent unauthorised access.</li>
              </ol>
            </section>

            <section className="legal-section">
              <h2>Amendments</h2>
              <p>The Company may alter or amend this Policy or any part thereof at any time. Data Subjects will be required to ensure that they keep up to date with the latest version of this Policy, as will be made available by the Company at https://pov-reality.com/</p>
            </section>

            <section className="legal-section">
              <h2>Contact Details</h2>
              <p>For all questions or concerns regarding the processing of your Personal Data, our contact details are as provided below:</p>
              <p>POV Reality Limited<br />
              England and Wales<br />
              Data Protection Lead<br />
              Tel: +44 7704 659886<br />
              E-Mail: admin@pov-reality.com</p>
            </section>
          </div>
        </div>
      </main>
    </>
  );
};

export default PrivacyPolicy; 